site_name: Bookmark Plus Docs
theme:
  logo: assets/bplus-logo.png
  name: material
  features:
    - header.autohide
    - navigation.footer
  font:
    text: Lexend Deca
  palette:
    primary: custom
  

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/vidura-labs
    - icon: fontawesome/brands/github 
      link: https://github.com/narenaryan/vidura-bookmark-plus-docs

copyright: '@ 2024 Vidura Labs. All rights reserved. Made with ♥ by <a href="https://vidura.ai/" target="_blank">Vidura Labs</a>'