name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Build and deploy
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mkdocs_version: 1.0.0
